### ISSUE TITLE
Train Quickaction is missing

### ISSUE THREAD

**Issue by janvandenbroeck** [mshanemc/einsteinVision#1]
Hi Shane,

When deploying your code, there is an error
`layouts/VisionModel__c-Vision Model Layout.layout -- Error: In field: QuickAction - no QuickAction named VisionModel__c.Train found
`

This is because QuickActions need to be retrieved as a separate metadata component. Easy to work around by removing the QuickAction but it would be great to have the complete package :)

Jan

**Comment by mshanemc** [comment]
Good catch...I'm working with our API team to resolve something about how /train is being called--once that's confirmed, I'll add the action.

**Comment by mshanemc** [comment]
Jan, we've got the API thing finished now.  

What's the issue with QuickAction?  I see it in the repo here...what am I missing?

**Comment by janvandenbroeck** [comment]
Hey Shane, when deploying: quickActions/VisionModel__c.Train.quickAction(VisionModel__c.Train):You can only create Lightning Component Quick Actions for Component Bundles containing a component that implements force:lightningQuickAction and has no required attributes without a default value.

**Comment by mshanemc** [comment]
Does it seem like the component meets those criteria, though?

https://github.com/mshanemc/einsteinVision/blob/master/src/aura/ModelTrainAction/ModelTrainAction.cmp

Just trying to figure out if my stuff is bad or the metadata API has some issue, or maybe it's the deployment tool.  Are you deploying via the button or via an IDE?

**Comment by mshanemc** [comment]
Oh, it's a known issue, waiting for spring17 fix.
https://success.salesforce.com/issues_view?id=a1p3A000000ei4BQAQ

**Comment by afawcett** [comment]
@mshanemc  and @janvandenbroeck are either of you still getting this? Because I am. It despite the known issue saying its fixed. Thoughts?

**Comment by mshanemc** [comment]
@afawcett Yeah.  Do you think it's metadata api problem, or my package, or the githubsfdeploy button?

**Comment by janvandenbroeck** [comment]
@mshanemc Im thinking it's the sfdeploy feature. I tried recently via sfdeploy and got the error. Downloaded the package and deployed with ant and it worked

**Comment by afawcett** [comment]
@janvandenbroeck Ah interesting..... so in my tests the API version of package.xml and components was all 38, however my ant-salesforce.jar may have been old (hence it itself maybe using an older MD API endpoint...) this is likely the case for sfdeploy button. I will look into this closer thanks!

**Comment by mshanemc** [comment]
@afawcett so to keep sfdeploy up to date as new features roll out, you almost need to bump up the MDAPI endpoint each time?
