### ISSUE TITLE
Deployment failing on EinsteinSignup Component 

### ISSUE THREAD

**Issue by jlondrejcka** [mshanemc/einsteinVision#3]
Hi Shane, 

FYI, this component is failing when I try deploying: EinsteinSignup.cmp

I think you may have had it as an apex class before, and now built into the js of the component. 

Failures:
aura/EinsteinSignup/EinsteinSignup.cmp(EinsteinSignup):Invalid definition for null:EinsteinSignup: null

Thanks, 

Joe

**Comment by mshanemc** [comment]
you're right--that should not be part of this project.  I removed it from the codebase.

**Comment by jlondrejcka** [comment]
Awesome, keep up the great work!
